name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./Cricket-project/ -t shyamsagane/Cricket-project:latest
    - name: push image to docker hub 
      run: | 
        docker login -u shyamsagane -p ${{secrets.DOCKER_HUB_TOKEN}}
        docker push shyamsagane/Cricket-project:latest
